services:
  bazel:
    image: codeforafrica/bazel:latest
    build:
      context: .

    environment:
      - TWOOPSTRACKER_ALLOWED_HOSTS=${TWOOPSTRACKER_ALLOWED_HOSTS:-*}
      - TWOOPSTRACKER_DATABASE_URL=${TWOOPSTRACKER_DATABASE_URL:-postgresql://twoops_tracker:twoops_tracker@db:5432/twoops_tracker}
      - TWOOPSTRACKER_DEBUG=${TWOOPSTRACKER_DEBUG:-True}
      - TWOOPSTRACKER_CELERY_BROKER_URL=${TWOOPSTRACKER_CELERY_BROKER_URL:-redis://redis:6379/0}
      - TWOOPSTRACKER_GOOGLE_OAUTH2_CLIENT_ID=${TWOOPSTRACKER_GOOGLE_OAUTH2_CLIENT_ID:-}
      - TWOOPSTRACKER_GOOGLE_OAUTH2_CLIENT_SECRET=${TWOOPSTRACKER_GOOGLE_OAUTH2_CLIENT_SECRET:-}
      # psql connection parameters (used in wait-for-postgrsql.sh)
      # see: https://www.postgresql.org/docs/13.4/libpq-envars.html
      - PGHOST=db
      - PGUSER=twoops_tracker
      - PGPASSWORD=twoops_tracker
      - PGDATABASE=twoops_tracker
    
    volumes:
      - ${APP_VOLUME:-app-files}:/app
    env_file:
      - .env
    
    ports:
      - ${TWOOPSTRACKER_PORT:-8000}:8000

  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  db-data:
  app-files:
