services:
  bazel:
    image: codeforafrica/bazel:latest
    build:
      context: .

    volumes:
      - ${APP_VOLUME:-app-files}:/app
    env_file:
      - .env
    
    ports:
      - ${TWOOPSTRACKER_PORT:-8000}:8000

  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    
  redis:
    restart: always
    image: redis:6.2
    expose:
      - "6379"

volumes:
  db-data:
  app-files:
